
project_id = "ufhcicqixojqpyykjljw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 600
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template = { invite = "", confirmation = "", recovery = "", magic_link = "", email_change = "" }

[auth.sms]
enable_signup = true
enable_confirmations = false
template = "Your code is {{ .Code }}"

[edge_functions]
enabled = true
inspector_port = 8083

[functions.cloudmailin-webhook]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.secure-contact]
verify_jwt = false
